name: 'lint/build/test'
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - develop
jobs:
  build:
    name: Lint, Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install dependencies
        run: |
          corepack enable
          yarn install

      - name: Lint source
        run: |
          yarn run lint:ci

      - name: Build apps and packages
        run: |
          yarn run build:ci

      - name: Run tests
        run: |
          yarn run test:ci
        env:
          CI: true
